<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="15798" started-at="2020-03-13T08:53:47Z" finished-at="2020-03-13T08:54:03Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="15798" started-at="2020-03-13T08:53:47Z" finished-at="2020-03-13T08:54:03Z">
      <class name="test.homepagetest">
        <test-method status="PASS" signature="pagenavigation()[pri:0, instance:test.homepagetest@1a18644]" name="pagenavigation" duration-ms="9476" started-at="2020-03-13T14:23:47Z" finished-at="2020-03-13T14:23:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pagenavigation -->
        <test-method status="PASS" signature="verifyTabs()[pri:0, instance:test.homepagetest@1a18644]" name="verifyTabs" duration-ms="890" started-at="2020-03-13T14:23:57Z" finished-at="2020-03-13T14:23:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTabs -->
        <test-method status="FAIL" signature="verifymessage()[pri:0, instance:test.homepagetest@1a18644]" name="verifymessage" duration-ms="5283" started-at="2020-03-13T14:23:58Z" finished-at="2020-03-13T14:24:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at test.homepagetest.verifymessage(homepagetest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifymessage -->
      </class> <!-- test.homepagetest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
